module.exports = {
  SECTION_ADDED: "SECTION_ADDED",
  CARD_ADDED: "CARD_ADDED",
  ON_SECTION_POS_CHANGE: "ON_SECTION_POS_CHANGE",
  ON_CARD_POS_CHANGE: "ON_CARD_POS_CHANGE",
  CARD_DELETED: "CARD_DELETED",
  LIST_DELETED: "LIST_DELETED",
};
